version: '3.3'
services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    server:
      build:
        context: ./source
        dockerfile: ./Dockerfile
      command: bash -c "
        python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000
        "
      env_file:
        - .env
      volumes:
        - ./source/:/code
      ports:
        - '8000:8000'
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      depends_on:
        - db
    test:
      build:
        context: ./source
        dockerfile: ./Dockerfile
      command: python manage.py test
      depends_on:
        - server
    bot:
        build:
          context: ./tg_bot
          dockerfile: ./Dockerfile
        command: python main.py
        volumes:
          - ./tg_bot/:/code
        env_file:
          - .env
    redis:
        image: 'redis'
        ports:
          - '6379:6379'
        command: redis-server --appendonly yes
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
