# Generated by Django 4.1.7 on 2023-02-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_client_payment_at_client_payment_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=77, verbose_name='Название группы')),
                ('start_at', models.TimeField(verbose_name='Время занятий')),
            ],
        ),
    ]
