# Generated by Django 4.1.7 on 2023-02-28 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата проведения тренировки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='webapp.client', verbose_name='Клиент')),
            ],
        ),
    ]
