# Generated by Django 4.1.7 on 2023-02-28 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_name', models.CharField(max_length=50, verbose_name='Telegram')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('started_to_work', models.DateField(verbose_name='Начало работы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Заработная плата')),
                ('salary_date', models.DateField(verbose_name='Дата зарплаты')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainers', to='webapp.group', verbose_name='Группа')),
            ],
        ),
    ]
