# Generated by Django 4.1.7 on 2023-02-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='webapp.coach', verbose_name='Тренер'),
        ),
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='client',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='webapp.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Регион'),
        ),
    ]
