# Generated by Django 4.1.7 on 2023-02-28 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_client_coach_client_comment_client_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='webapp.coach', verbose_name='Тренер'),
        ),
    ]
