# Generated by Django 4.1.7 on 2023-03-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_coach_group_group_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='coach',
        ),
    ]
