# Generated by Django 4.1.7 on 2023-03-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_client_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='salary_date',
        ),
    ]
