# Generated by Django 4.1.7 on 2023-03-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_coach_salary_remove_coach_salary_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coach_trainings', to='webapp.coach', verbose_name='Тренер')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_trainings', to='webapp.group', verbose_name='Группа')),
            ],
        ),
    ]
