# Generated by Django 4.1.7 on 2023-03-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_coachtraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='webapp.group', verbose_name='Группа'),
        ),
    ]
