# Generated by Django 4.1.7 on 2023-03-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_client_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoachTraining',
            new_name='GroupTraining',
        ),
    ]
