# Generated by Django 4.1.7 on 2023-03-31 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_payment_created_at_payment_updated_at'),
        ('webapp', '0016_rename_coachtraining_grouptraining'),
    ]

    operations = [
    ]
