# Generated by Django 4.1.7 on 2023-04-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_client_photo_coach_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='webapp.coach', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='grouptraining',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_trainings', to='webapp.coach', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='grouptraining',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_trainings', to='webapp.group', verbose_name='Группа'),
        ),
    ]
