# Generated by Django 4.1.7 on 2023-04-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_group_coach_alter_grouptraining_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='webapp.group', verbose_name='Группа'),
        ),
    ]
