# Generated by Django 4.1.7 on 2023-04-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_client_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='first_name',
            field=models.CharField(default=1, max_length=20, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
